import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState, useRef, useEffect } from "react";

export default function Home() {
  const sectionRef = useRef(null);
  const [input, setInput] = useState("");
  const [chatLog, setChatLog] = useState([
    {
      user: "gbt",
      message: "GM GM",
    },
    {
      user: "gbt",
      message: "How Can I Help You Debug?",
    },
    {
      user: "gbt",
      message: "Ask me anything!",
    },
  ]);

  useEffect(() => {
    console.log("bing bong");
    scrollToBottom();
  }, [chatLog]);

  function clearChat() {
    setChatLog([]);
  }

  function scrollToBottom() {
    console.log("scrolling to bottom");
    sectionRef.current.scrollIntoView({ behavior: "smooth", block: "end" });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    console.log("submit");
    let chatLogNew = [...chatLog, { user: "me", message: `${input}` }];
    await setInput("");
    const messages = chatLogNew.map((message) => message.message).join("\n");
    const response = await fetch("http://localhost:3080/", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        message: messages,
      }),
    });
    const data = await response.json();
    await setChatLog([
      ...chatLogNew,
      { user: "gbt", message: `${data.message}` },
    ]);
  }
  return (
    <>
      <Head>
        <title>HelpMeDebugThis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid lg:grid-cols-5">
        {/* SECTION ONE START */}
        <div className="appPanelOneBody bg-gray-200 lg:col-span-2 h-fit lg:h-screen">
          <div className="appPanelOneContainer px-8 py-12 max-w-md mx-auto sm:max-w-xl">
            <img
              className="h-14 mx-auto sm:h-16"
              src="/img/logo-black.svg"
              alt="HelpMeDebugThisLog"
            ></img>
            <img
              className="mt-3 mx-auto"
              src="/img/robot.svg"
              alt="HelpMeDebugThisLog"
            ></img>
            <h1 className="mt-2 text-2xl font-bold sm:text-3xl">
              Talk to our <span className="text-[#71bd57]">A.I. chatbot</span>{" "}
              <br /> A smart assistant always by your side{" "}
            </h1>
            <p className="mt-2 text-gray-600 sm:text-xl sm:mt-4">
              HelpMeDebugThis is an A.I powered chatbot designed to answer any
              question, anytime, anywhere. Chat with me today. Beep Boop.
            </p>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="mt-7 w-6 h-6 mx-auto lg:hidden"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M19.5 5.25l-7.5 7.5-7.5-7.5m15 6l-7.5 7.5-7.5-7.5"
              />
            </svg>
          </div>
        </div>

        {/* SECTION TWO START */}
        <div className="appPanelTwoBody lg:col-span-3 text-white">
          <div className="appPanelTwoContainer lg:h-screen min-w-full px-12 py-5 mx-auto sm:max-w-xl border bg-[#343542] border-[#5F646C]">
            <div className="chatHeader h-10 border border-[#5F646C] flex p-2 justify-between">
              <div className="iconClearChat">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-6 h-6"
                  onClick={clearChat}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
                  />
                </svg>
              </div>
              <div className="iconScrollDown">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-6 h-6"
                  onClick={scrollToBottom}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M19.5 13.5L12 21m0 0l-7.5-7.5M12 21V3"
                  />
                </svg>
              </div>
            </div>
            <div className="chatLog flex flex-col max-h-[43rem] min-h-[43rem] overflow-auto border-2 border-[#5F646C] space-y-2 p-2 rounded">
              {chatLog.map((message, index) => (
                <ChatMessage key={index} message={message} />
              ))}
              {/* <div className="chat-box-left">GM!</div>
              <div className="chat-box-left">Bing Bong</div>
              <div className="chat-box-left">Hey I'm a robot BEEP BOOP</div>
              <div className="chat-box-left">
                I'm a robot and I can do whatever you waht, ask me something go
                ahead, ask me ask me ask me
              </div>
              <div className="chat-box-right">
                ullamcorper, sollicitudin leo vitae, egestas elit. Nulla
                tristique sed lectus eu eleifend. Morbi facilisis nunc turpis,
                vel iaculis justo viverra quis. Pellentesque feugiat velit sed
                risus interdum, vel maximus purus gravida.
              </div>
              <div className="chat-box-right">
                eros urna rhoncus risus, vitae ultricies nibh diam sit amet
                tortor. Sed congue justo eget consectetur fermentum. Nam commodo
                velit sed cursus blandit.
              </div>
              <div className="chat-box-left">
                Fusce pretium nisl a luctus dapibus. Vivamus efficitur tellus ac
                dolor tincidunt tempus. Vestibulum ante ipsum primis in faucibus
                orci luctus et ultrices posuere cubilia curae; In vel justo
                lectus. Vestibulum eget odio nisi. Curabitur ac mi sed ante
                luctus dictum. Cras et auctor nisi, sit amet malesuada dolor.
              </div>
              <div className="chat-box-right">Bing Bong</div>
              <div className="chat-box-right">Roll it up young bllllssss</div>
              <div className="chat-box-left">
                Fusce pretium nisl a luctus dapibus. Vivamus efficitur tellus ac
                dolor tincidunt tempus. Vestibulum ante ipsum primis in faucibus
                orci luctus et ultrices posuere cubilia curae;
              </div>
              <div className="chat-box-right">BEEP BOOP</div>
              <div className="chat-box-right">BEEP BOOP</div>
              <div className="chat-box-right">BEEP BOOP</div>
              <div className="chat-box-right">BEEP BOOP</div> */}
              {/* <div className="h-10" ref={sectionRef}></div> */}
              <br ref={sectionRef} />
            </div>
            <div className="chatInput max-w-md flex mt-5 mx-auto">
              <form className="w-full" onSubmit={handleSubmit}>
                <input
                  className="h-10 w-full appearance-none rounded p-2 text-white bg-[#40414f] focus:outline-none focus:shadow-outline"
                  id="username"
                  type="text"
                  placeholder="Ask me a something"
                  autoComplete="off"
                  rows="1"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                />
              </form>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-9 h-9 ml-2"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
                />
              </svg>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

const ChatMessage = ({ message }) => {
  return (
    <div
      className={message.user === "gbt" ? "chat-box-left" : "chat-box-right"}
    >
      <div className="">{message.message}</div>
    </div>
  );
};
