import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="appBody bg-gray-200 sm:bg-yellow-200">
        <div className="appHeader px-8 py-12 max-w-md mx-auto sm:max-w-xl">
          <img
            className="h-10 mx-auto sm:h-16"
            src="/img/logo-black.svg"
            alt="HelpMeDebugThisLog"
          ></img>
          <img
            className="mt-5 mx-auto"
            src="/img/robot.svg"
            alt="HelpMeDebugThisLog"
          ></img>
          <h1 className="mt-2 text-2xl font-bold sm:text-4xl">
            Talk to our <span className="text-green-700">A.I. chatbot</span>{" "}
            <br /> A smart assistant always by your side{" "}
          </h1>
          <p className="mt-2 text-gray-600 sm:text-xl sm:mt-4">
            HelpMeDebugThis is an A.I powered chatbot designed to answer any
            question, anytime, anywhere. Chat with me today. Beep Boop.
          </p>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="mt-7 w-6 h-6 mx-auto"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M19.5 5.25l-7.5 7.5-7.5-7.5m15 6l-7.5 7.5-7.5-7.5"
            />
          </svg>
        </div>
      </div>
    </>
  );
}
